!ArenaConfig
arenas:
  0: !Arena
    t: 0
    rand_all_colors: true
    items:
    - !Item
      name: CubeTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CylinderTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cylinder
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Ramp
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Wall
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WallTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cube
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CubeTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox1
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox2
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WoodLog
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: UObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: LObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: DeathZone
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: MazeGenerator
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMove
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalBounce
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoalMove
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoalBounce
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMultiMove
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMultiBounce
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  1: !Arena
    t: 0
    rand_all_colors: false
    items:
    - !Item
      name: CubeTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cylinder
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CylinderTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Ramp
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Wall
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WallTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cube
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CubeTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox1
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox2
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WoodLog
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: UObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: LObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: DeathZone
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: MazeGenerator
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  2: !Arena
    t: 0
    rand_all_colors: false
    items:
    - !Item
      name: CubeTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cylinder
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CylinderTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Ramp
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Wall
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WallTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cube
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CubeTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox1
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox2
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WoodLog
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: UObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: LObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: DeathZone
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: MazeGenerator
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  3: !Arena
    t: 0
    rand_all_colors: false
    items:
    - !Item
      name: CubeTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cylinder
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CylinderTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Ramp
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Wall
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WallTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cube
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CubeTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox1
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox2
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WoodLog
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: UObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: LObject
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: DeathZone
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: MazeGenerator
      positions: []
      rand_color: false
      rotations: []
      sizes: []

