!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    rand_all_colors: true
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  1: !Arena
    t: 1000
    rand_all_colors: true
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  2: !Arena
    t: 1000
    rand_all_colors: true
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  3: !Arena
    t: 1000
    rand_all_colors: true
    items:
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []