!ArenaConfig
arenas:
  0: !Arena
    t: 0
    rand_all_colors: true
    rand_all_sizes: true
    items:
    - !Item
      name: GoodGoalBounce
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoalBounce
      positions: []
      rand_color: false
      rotations: []
      sizes: []